#!/bin/sh
#
# Automatically adds task name and branch description to every commit message.
# Expected branch name .*/TASK-1234/.*
#
COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

REGEX_ISSUE_ID="[a-zA-Z0-9,\.\_\-]+-[0-9]+"
BRANCH_NAME=$(git symbolic-ref --short HEAD)

if [[ -z "$BRANCH_NAME" ]]; then
    echo "No branch name... "; exit 1
fi

KNOWN_ISSUE_ID=$(grep -o -E "^$REGEX_ISSUE_ID" "$COMMIT_MSG_FILE")
ISSUE_ID=$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID")

if ("$KNOWN_ISSUE_ID" == "$ISSUE_ID"); then
  exit 0
fi

addIssueId() {
  DESCRIPTION=$(git config branch."$BRANCH_NAME".description)

  if [ -n "$COMMIT_MSG_FILE" -a -n "$ISSUE_ID" ]; then
    echo "$ISSUE_ID"': '$(cat "$COMMIT_MSG_FILE") > "$COMMIT_MSG_FILE"
  fi
  if [ -n "$DESCRIPTION" ]; then
    echo "" >> "$COMMIT_MSG_FILE"
    echo $DESCRIPTION >> "$COMMIT_MSG_FILE"
  fi
}

# The merge-commit has branch information by default so extra branch name is
# unnecessary and make the message ugly.
MERGE=$(cat "$COMMIT_MSG_FILE" | grep -i 'merge' | wc -l)
if [ $MERGE -eq 0 ] ; then
  addIssueId
fi
